_wandb:
    value:
        cli_version: 0.23.1
        e:
            ls21zjj0uoor4wjroyt0m1cykyzx5dt6:
                codePath: run_exp.py
                codePathLocal: run_exp.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "52573995008"
                        used: "39326638080"
                email: eop.l.8xil@gmail.com
                executable: /data/ephemeral/home/.venv/bin/python
                git:
                    commit: 00b9edf59fcc88e3403b1334ebf058225d202b91
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-a03ecb06-9615-b2bc-6949-238d03e2b717
                host: instance-17653
                memory:
                    total: "94903173120"
                os: Linux-5.4.0-99-generic-x86_64-with-glibc2.31
                program: /data/ephemeral/home/work/run_exp.py
                python: CPython 3.10.13
                root: /data/ephemeral/home/work
                startedAt: "2025-12-25T13:17:55.559776Z"
                writerId: ls21zjj0uoor4wjroyt0m1cykyzx5dt6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 74
                - 80
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 74
                - 80
            "3":
                - 13
                - 16
            "4": 3.10.13
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 8
dataloader:
    value: DALI
dataset_file:
    value: dataset.dataset_dali_sliding
epochs:
    value: 50
learning_rate:
    value: 0.0001
loss_function:
    value: Dice
optimizer:
    value: AdamW
scheduler:
    value: None
